openapi: 3.0.0
info:
  title: School Newsfeed API
  description: School Newsfeed API Document
  version: 0.1.9
servers:
  - url: http://localhost:80
    description: localhost

paths:
  /admin:
    get:
      summary: 현재 등록된 관리자 목록
      tags:
        - 관리자
      parameters:
        - in: path
          name: adminIdx
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    adminIdx:
                      type: integer
                    adminName:
                      type: string
                    schoolIdx:
                      type: integer
                    schoolName:
                      type: string

  /school:
    post:
      summary: 학교 등록
      description: 관리자가 학교 생성
      tags:
        - 학교
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                adminIdx:
                  type: integer
                name:
                  type: string
                region:
                  type: string
              required:
                - adminIdx
                - name
                - region
      responses:
        "200":
          description: success
        "400":
          description: 리퀘스트 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string

  /post:
    post:
      summary: 소식 등록
      tags:
        - 소식
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                schoolIdx:
                  type: integer
                adminIdx:
                  type: integer
                subject:
                  type: string
                content:
                  type: string
              required:
                - schoolIdx
                - adminIdx
                - subject
                - content
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  postIdx:
                    type: integer
                  createdAt: 
                    type: string
        "400":
          description: 리퀘스트 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string

    put:
      summary: 소식 수정
      tags:
        - 소식
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                postIdx:
                  type: integer
                schoolIdx:
                  type: integer
                adminIdx:
                  type: integer
                subject:
                  type: string
                content:
                  type: string
              required:
                - postIdx
                - schoolIdx
                - adminIdx
                - subject
                - content
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  postIdx:
                    type: integer
                  updatedAt: 
                    type: string
        "400":
          description: 리퀘스트 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        "404":
          description: 해당 소식이 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    
                    
  /post/:postIdx:
    delete:
      summary: 소식 삭제
      tags:
        - 소식
      parameters:
        - in: path
          name: postIdx
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: a json array of cities
          content:
            application/json:
              schema: 
                type: object
                properties:
                  cityIdx:
                    type: integer
        "400":
          description: 리퀘스트 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        "404":
          description: 해당 소식이 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
  
  /subs:
    post:
      summary: 학교 구독 등록
      tags:
        - 구독
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                studentIdx:
                  type: integer
                schoolIdx:
                  type: integer
              required:
                - studentIdx
                - schoolIdx
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  subsIdx:
                    type: integer
                  studentIdx: 
                    type: integer
                  schoolIdx:
                    type: integer
                  startDate:
                    type: string
        "400":
          description: 리퀘스트 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string                    

    delete:
      summary: 학교 구독 취소
      tags:
        - 구독
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                studentIdx:
                  type: integer
                schoolIdx:
                  type: integer
              required:
                - studentIdx
                - schoolIdx
      responses:
        "200":
          description: 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  studentIdx: 
                    type: integer
                  schoolIdx:
                    type: integer
                  endDate:
                    type: string
        "400":
          description: 리퀘스트 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        "404":
          description: 정보에 해당하는 구독이 존재하지 않음
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: 정보에 해당하는 구독 없음


  /subs/:studentIdx:
    get:
      summary: 현재 구독중인 학교 리스트
      tags:
        - 구독
      parameters:
        - in: path
          name: studentIdx
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  studentIdx:
                    type: integer
                  studentName:
                    type: string
                  schools:
                    type: array
                    items:
                      type: object
                      properties:
                        schoolIdx:
                          type: integer
                        schoolName:
                          type: string
                        startDate:
                          type: string
        "400":
          description: 파라미터 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        "404":
          description: 구독하는 학교 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: 구독중인 학교가 없습니다.
  
  /newsfeed/:studentIdx:
    get:
      summary: 구독중인 소식 뉴스피드
      tags:
        - 뉴스피드
      parameters:
        - in: path
          name: studentIdx
          schema:
            type: integer
          required: true
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  studentIdx:
                    type: integer
                  studentName:
                    type: string
                  posts:
                    type: array
                    items:
                      type: object
                      properties:
                        schoolName:
                          type: string
                        date:
                          type: string
                        subject:
                          type: string
                        content:
                          type: string
        "400":
          description: 파라미터 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
        "404":
          description: 조회된 소식 없음
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string               


      

